import { ArrowLeft, History, Printer } from "lucide-react";
import Link from "next/link";
import { notFound } from "next/navigation";

import { ContentContainer, PageHeader } from "@/src/components/layout";
import { Badge, Card, CardContent, Table, TableCell, TableContainer, TableHead } from "@/src/components/ui";
import { getSaleDetail } from "@/src/services/sales/sales";

const currency = new Intl.NumberFormat("es-EC", { style: "currency", currency: "USD" });
const dateFormatter = new Intl.DateTimeFormat("es-EC", { timeZone: "America/Guayaquil", dateStyle: "long", timeStyle: "short" });

export default async function SaleDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const sale = await getSaleDetail(Number(id));
  if (!sale) notFound();
  return <ContentContainer>
    <PageHeader eyebrow="Detalle de venta" title={sale.numero_venta} description={`Registrada el ${dateFormatter.format(new Date(sale.fecha))}`} actions={<><Link href="/ventas/historial" className="inline-flex h-11 items-center gap-2 rounded-xl border bg-lf-surface px-4 text-sm font-semibold"><ArrowLeft size={17} /> Historial</Link><Link href={`/ventas/${sale.id_venta}/comprobante`} className="inline-flex h-11 items-center gap-2 rounded-xl bg-lf-terracotta px-4 text-sm font-semibold text-white"><Printer size={17} /> Comprobante</Link></>} />
    <div className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_20rem]">
      <div className="space-y-5"><Card><CardContent className="p-0"><TableContainer className="border-0 shadow-none"><Table><thead><tr><TableHead>Producto</TableHead><TableHead>Cantidad</TableHead><TableHead>Precio</TableHead><TableHead>Descuento</TableHead><TableHead>Subtotal</TableHead><TableHead>IVA</TableHead><TableHead>Total</TableHead></tr></thead><tbody>{sale.items.map((item) => { const discount = item.precio_unitario * item.cantidad - item.total; return <tr key={item.id_detalle}><TableCell><p className="font-semibold">{item.producto}</p><p className="font-mono text-xs text-lf-muted">{item.codigo_gs1}</p></TableCell><TableCell>{item.cantidad}</TableCell><TableCell>{currency.format(item.precio_unitario)}</TableCell><TableCell>{currency.format(Math.max(0, discount))}</TableCell><TableCell>{currency.format(item.subtotal)}</TableCell><TableCell>{currency.format(item.iva)}</TableCell><TableCell className="font-bold">{currency.format(item.total)}</TableCell></tr>; })}</tbody></Table></TableContainer></CardContent></Card>
        <Card><CardContent><div className="flex items-center gap-2"><History size={19} className="text-lf-terracotta" /><h2 className="font-semibold">Auditoría relacionada</h2></div>{sale.audit.length ? <ol className="mt-4 divide-y">{sale.audit.map((entry) => <li key={entry.id} className="grid gap-2 py-3 text-sm sm:grid-cols-[10rem_9rem_1fr]"><time className="text-lf-muted">{dateFormatter.format(new Date(entry.date))}</time><div><Badge variant={entry.action === "ANULACION" || entry.action === "DELETE" ? "danger" : entry.action === "VENTA" || entry.action === "INSERT" ? "success" : "neutral"}>{entry.action}</Badge></div><div><p><strong>{entry.user}</strong> · {entry.table}</p>{entry.action === "UPDATE" && entry.previousValue && entry.newValue ? <p className="mt-1 text-xs text-lf-muted">Actualización registrada con valores anteriores y nuevos.</p> : null}</div></li>)}</ol> : <p className="mt-4 text-sm text-lf-muted">No hay eventos de auditoría asociados.</p>}</CardContent></Card></div>
      <aside className="space-y-5"><Card><CardContent><div className="flex items-center justify-between"><h2 className="font-semibold">Venta</h2><Badge variant={sale.estado === "REGISTRADA" ? "success" : sale.estado === "ANULADA" ? "danger" : "neutral"}>{sale.estado}</Badge></div><dl className="mt-4 space-y-3 text-sm"><div><dt className="text-lf-muted">Cliente</dt><dd className="font-semibold">{sale.cliente}</dd>{sale.identificacion ? <dd className="text-xs text-lf-muted">{sale.identificacion}</dd> : null}</div><div><dt className="text-lf-muted">Vendedor</dt><dd>{sale.vendedor}</dd></div><div><dt className="text-lf-muted">Local / Canal</dt><dd>{sale.local} · {sale.canal}</dd></div></dl></CardContent></Card><Card><CardContent><h2 className="font-semibold">Totales</h2><dl className="mt-4 space-y-3 text-sm"><div className="flex justify-between"><dt>Subtotal</dt><dd>{currency.format(sale.subtotal)}</dd></div><div className="flex justify-between"><dt>Descuento</dt><dd>−{currency.format(sale.descuento)}</dd></div><div className="flex justify-between"><dt>IVA</dt><dd>{currency.format(sale.iva)}</dd></div><div className="flex justify-between border-t pt-3 text-lg font-bold"><dt>Total</dt><dd>{currency.format(sale.total)}</dd></div></dl></CardContent></Card><Card><CardContent><h2 className="font-semibold">Pagos</h2><div className="mt-4 space-y-3">{sale.pagos.map((payment) => <div key={payment.id_pago} className="flex justify-between gap-3 text-sm"><span>{payment.forma}{payment.referencia ? <small className="block text-lf-muted">Ref. {payment.referencia}</small> : null}</span><strong>{currency.format(payment.valor)}</strong></div>)}</div></CardContent></Card></aside>
    </div>
  </ContentContainer>;
}
