import { AlertTriangle, BellRing, Boxes, Clock3, CreditCard, PackageX, Search } from "lucide-react";
import Link from "next/link";

import { ContentContainer, PageHeader } from "@/src/components/layout";
import { Badge, Card, CardContent } from "@/src/components/ui";
import { getAlerts } from "@/src/services/alerts/alerts";

export default async function AlertsPage({ searchParams }: { searchParams: Promise<{ tipo?: string }> }) {
  const { tipo = "" } = await searchParams;
  const data = await getAlerts(tipo);
  return <ContentContainer>
    <PageHeader eyebrow="Centro de alertas" title="Alertas" description="Situaciones que requieren atención para mantener la operación al día." actions={<Link href="/inventario" className="inline-flex h-11 items-center gap-2 rounded-xl border bg-lf-surface px-4 text-sm font-semibold"><Boxes size={17} /> Ver inventario</Link>} />
    <div className="mb-6 grid gap-4 sm:grid-cols-3"><Link href="/alertas" className={`rounded-2xl border p-5 shadow-[var(--lf-shadow-sm)] ${!data.type ? "border-lf-navy bg-lf-navy text-white" : "bg-lf-surface"}`}><p className="text-sm opacity-75">Alertas activas</p><p className="mt-1 text-3xl font-bold">{data.summary.total}</p></Link><Link href="/alertas?tipo=minimo" className={`rounded-2xl border p-5 shadow-[var(--lf-shadow-sm)] ${data.type === "minimo" ? "border-lf-warning bg-[var(--lf-warning-soft)]" : "bg-lf-surface"}`}><p className="text-sm text-lf-muted">Stock mínimo</p><p className="mt-1 text-3xl font-bold text-lf-warning">{data.summary.low}</p></Link><Link href="/alertas?tipo=agotado" className={`rounded-2xl border p-5 shadow-[var(--lf-shadow-sm)] ${data.type === "agotado" ? "border-lf-danger bg-[var(--lf-danger-soft)]" : "bg-lf-surface"}`}><p className="text-sm text-lf-muted">Productos agotados</p><p className="mt-1 text-3xl font-bold text-lf-danger">{data.summary.out}</p></Link></div>
    <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_19rem]"><section>{data.alerts.length ? <div className="space-y-3">{data.alerts.map((alert) => { const out = alert.type === "OUT_OF_STOCK"; return <article key={alert.id_stock} className="flex flex-col gap-4 rounded-2xl border bg-lf-surface p-4 shadow-[var(--lf-shadow-sm)] sm:flex-row sm:items-center"><span className={`grid size-12 shrink-0 place-items-center rounded-xl ${out ? "bg-[var(--lf-danger-soft)] text-lf-danger" : "bg-[var(--lf-warning-soft)] text-lf-warning"}`}>{out ? <PackageX size={22} /> : <AlertTriangle size={22} />}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><Link href={`/productos/${alert.id_producto}`} className="font-semibold hover:text-lf-terracotta">{alert.producto}</Link><Badge variant={out ? "danger" : "warning"}>{out ? "Agotado" : "Stock mínimo"}</Badge></div><p className="mt-1 text-sm text-lf-muted">{alert.bodega} · <span className="font-mono">{alert.codigo_gs1}</span></p></div><div className="text-left sm:text-right"><p className={`text-2xl font-bold ${out ? "text-lf-danger" : "text-lf-warning"}`}>{alert.stock_actual}</p><p className="text-xs text-lf-muted">mínimo {alert.stock_minimo}</p></div></article>; })}</div> : <Card><CardContent className="grid min-h-64 place-items-center text-center"><div><BellRing size={34} className="mx-auto text-lf-success" /><p className="mt-3 font-semibold">Sin alertas activas</p><p className="mt-1 text-sm text-lf-muted">El inventario se encuentra dentro de los niveles esperados.</p></div></CardContent></Card>}</section>
      <aside className="h-fit rounded-2xl border bg-lf-surface p-5"><h2 className="font-semibold">Próximas alertas</h2><p className="mt-1 text-xs text-lf-muted">Estructura preparada para ampliar el sistema.</p><ul className="mt-4 space-y-3 text-sm"><li className="flex items-center gap-3 text-lf-muted"><Clock3 size={17} /> Pagos próximos</li><li className="flex items-center gap-3 text-lf-muted"><CreditCard size={17} /> Pagos vencidos</li><li className="flex items-center gap-3 text-lf-muted"><Search size={17} /> Baja rotación</li><li className="flex items-center gap-3 text-lf-muted"><AlertTriangle size={17} /> Cuentas pendientes</li></ul></aside>
    </div>
  </ContentContainer>;
}
